### ISSUE TITLE
No METASTOCK Data generated

### ISSUE THREAD

**Issue by normaltusker** [webshub/Shubha_Downloader#4]
Hi,
I used your program to download the EOD data and had selected the STD.CSV as well as Metastock. All I see is that the STD.CSV is copied to the Metastock folder and no Metastock data had been generated. Even the CSV cannot be converted to the Metastock format by "The Downloader" because of the presence of the name column. Can you please do something about it?

Infact, when I select Metastock, the message log looks like below. Don't you think It should say Metastock Finished? :)
loading...
C:/data/std_csv dir created succesfully....
C:/data/metastock dir created succesfully....
cm30JAN2013bhav.csv.zip is downloaded...
cm30JAN2013bhav.csv.zip is extracted...
MTO_30012013.DAT is downloaded ..
PR300113.zip is downloading..
sec_list is downloaded
PR300113.zip is downloaded...
PR300113.zip is extracted...
cm30Jan2013bhav.csv is processed..
pd300113.csv is processed..
metastock Nse_Cash_Market_cm30Jan2013bhav.csv is processed..
metastock NSE_Indices_nseindex.csv is processed..
Ninja finished

**Comment by webshub** [comment]
Thanks for reporting. Data is generated in ascii but it can be imported in MS using asc2ms. asc2ms is included.
We are now auto converting it to MS format in new builds (not released).

**Comment by webshub** [comment]
Please check new release and video. This feature is included now.
