### ISSUE TITLE
There is CSV File in Amibroker Folder--but it needs some type of proper auto formatting to import in Amibroker

### ISSUE THREAD

**Issue by asisjpg** [webshub/Shubha_Downloader#7]
File in Amibroker Folder--but it needs some type of proper auto formatting to import in Amibroker

ogging started for 'C:\data\amibroker\MCX_Com_mcxbhavcopyFeb262013.csv' file, using format definition file 'Formats\custom4.format'
Error in line ALMOND-II,ALMOND,20130226,0.00,0.00,0.00,468.25,468.25,0.00
Invalid (close) price. Prices must be positive. If you want to import no quotation data please specify $NOQUOTES 1 ('no quotation data' box in Wizard)
Invalid date format/value
Error in line ALUMINI-III,ALUMINI,20130226,111.30,111.80,110.75,111.05,111.95,34.45
Invalid date format/value
Error in line ALUMINI-II,ALUMINI,20130226,110.85,110.85,109.65,110.55,110.65,286.54
Invalid date format/value
Error in line ALUMINI-I,ALUMINI,20130226,109.30,109.50,108.25,109.20,109.25,6927.13
Invalid date format/value
Error in line ALUMINIUM-III,ALUMINIUM,20130226,112.05,112.05,110.95,111.35,111.90,144.76
Invalid date format/value

**Comment by webshub** [comment]
This is not a bug. Please watch video tutorial, it's shows how to import data. Amibroker accepts csv files.
